# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hold.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nhold.proto\x12\x04hold"\xc3\x01\n\x0eInvoiceRequest\x12\x14\n\x0cpayment_hash\x18\x01 \x01(\t\x12\x13\n\x0b\x61mount_msat\x18\x02 \x01(\x04\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06\x65xpiry\x18\x04 \x01(\x04H\x01\x88\x01\x01\x12"\n\x15min_final_cltv_expiry\x18\x05 \x01(\x04H\x02\x88\x01\x01\x42\x0e\n\x0c_descriptionB\t\n\x07_expiryB\x18\n\x16_min_final_cltv_expiry"!\n\x0fInvoiceResponse\x12\x0e\n\x06\x62olt11\x18\x01 \x01(\t")\n\rSettleRequest\x12\x18\n\x10payment_preimage\x18\x01 \x01(\t"\x10\n\x0eSettleResponse"%\n\rCancelRequest\x12\x14\n\x0cpayment_hash\x18\x01 \x01(\t"\x10\n\x0e\x43\x61ncelResponse"9\n\x0bListRequest\x12\x19\n\x0cpayment_hash\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_payment_hash"\x86\x01\n\x07Invoice\x12\x14\n\x0cpayment_hash\x18\x01 \x01(\t\x12\x1d\n\x10payment_preimage\x18\x02 \x01(\tH\x00\x88\x01\x01\x12!\n\x05state\x18\x03 \x01(\x0e\x32\x12.hold.InvoiceState\x12\x0e\n\x06\x62olt11\x18\x04 \x01(\tB\x13\n\x11_payment_preimage"/\n\x0cListResponse\x12\x1f\n\x08invoices\x18\x01 \x03(\x0b\x32\r.hold.Invoice"$\n\x0cTrackRequest\x12\x14\n\x0cpayment_hash\x18\x01 \x01(\t"2\n\rTrackResponse\x12!\n\x05state\x18\x01 \x01(\x0e\x32\x12.hold.InvoiceState*]\n\x0cInvoiceState\x12\x11\n\rInvoiceUnpaid\x10\x00\x12\x13\n\x0fInvoiceAccepted\x10\x01\x12\x0f\n\x0bInvoicePaid\x10\x02\x12\x14\n\x10InvoiceCancelled\x10\x03\x32\x95\x02\n\x04Hold\x12\x38\n\x07Invoice\x12\x14.hold.InvoiceRequest\x1a\x15.hold.InvoiceResponse"\x00\x12\x35\n\x06Settle\x12\x13.hold.SettleRequest\x1a\x14.hold.SettleResponse"\x00\x12\x35\n\x06\x43\x61ncel\x12\x13.hold.CancelRequest\x1a\x14.hold.CancelResponse"\x00\x12/\n\x04List\x12\x11.hold.ListRequest\x1a\x12.hold.ListResponse"\x00\x12\x34\n\x05Track\x12\x12.hold.TrackRequest\x1a\x13.hold.TrackResponse"\x00\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hold_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_INVOICESTATE"]._serialized_start = 706
    _globals["_INVOICESTATE"]._serialized_end = 799
    _globals["_INVOICEREQUEST"]._serialized_start = 21
    _globals["_INVOICEREQUEST"]._serialized_end = 216
    _globals["_INVOICERESPONSE"]._serialized_start = 218
    _globals["_INVOICERESPONSE"]._serialized_end = 251
    _globals["_SETTLEREQUEST"]._serialized_start = 253
    _globals["_SETTLEREQUEST"]._serialized_end = 294
    _globals["_SETTLERESPONSE"]._serialized_start = 296
    _globals["_SETTLERESPONSE"]._serialized_end = 312
    _globals["_CANCELREQUEST"]._serialized_start = 314
    _globals["_CANCELREQUEST"]._serialized_end = 351
    _globals["_CANCELRESPONSE"]._serialized_start = 353
    _globals["_CANCELRESPONSE"]._serialized_end = 369
    _globals["_LISTREQUEST"]._serialized_start = 371
    _globals["_LISTREQUEST"]._serialized_end = 428
    _globals["_INVOICE"]._serialized_start = 431
    _globals["_INVOICE"]._serialized_end = 565
    _globals["_LISTRESPONSE"]._serialized_start = 567
    _globals["_LISTRESPONSE"]._serialized_end = 614
    _globals["_TRACKREQUEST"]._serialized_start = 616
    _globals["_TRACKREQUEST"]._serialized_end = 652
    _globals["_TRACKRESPONSE"]._serialized_start = 654
    _globals["_TRACKRESPONSE"]._serialized_end = 704
    _globals["_HOLD"]._serialized_start = 802
    _globals["_HOLD"]._serialized_end = 1079
# @@protoc_insertion_point(module_scope)
