[package]
name = "boltz-core"
version = "0.0.1"
license.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["musig", "bitcoin"]
musig = ["dep:secp256k1"]
bitcoin = ["dep:bitcoin"]

[dependencies]
anyhow = { workspace = true }
hex = "0.4.3"
secp256k1 = { git = "https://github.com/rust-bitcoin/rust-secp256k1.git", version = "0.31.1", features = ["rand"], optional = true }
bitcoin = { workspace = true, optional = true }
serde.workspace = true

[dev-dependencies]
corepc-node = { version = "0.8.0", default-features = false, features = ["29_0"] }
rstest = { workspace = true }
serde_json = { workspace = true }
