name: Docker

on:
  push:
    branches:
      - add-elements-docker

env:
  IMAGE_NAME: ghcr.io/tiero/regtest
  UBUNTU_VERSION: "20.04" 
  BITCOIN_VERSION: "22.0" 
  LITECOIN_VERSION: "0.18.1" 
  ELEMENTS_VERSION: "0.21.0.1"
  LND_VERSION: "0.14.1-beta"
  
jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        working-directory: ./docker
        run:  >-
          docker buildx build 
          --file regtest/Dockerfile 
          --build-arg UBUNTU_VERSION=$UBUNTU_VERSION
          --build-arg BITCOIN_VERSION=$BITCOIN_VERSION
          --build-arg LITECOIN_VERSION=$LITECOIN_VERSION 
          --build-arg ELEMENTS_VERSION=$ELEMENTS_VERSION
          --build-arg LND_VERSION=$LND_VERSION
          --platform linux/amd64 
          --tag $IMAGE_NAME:latest 
          .

      - name: Push image
        run: docker push $IMAGE_NAME:latest
